#! /bin/sh

##  Win32 cross-compilation for libcaca -- Sam Hocevar <sam@zoy.org>
##  $Id$

set -x
set -e

# Clean up our working directory
DIRNAME="libcaca-win32-`sed -ne '/^VERSION/s/[^0-9]*//p' Makefile`"
DESTDIR="`pwd`/${DIRNAME}"
rm -Rf "${DIRNAME}"
rm -f "${DIRNAME}.zip"
mkdir "${DIRNAME}"

# Build for win32
./configure --host=i586-mingw32msvc --prefix=/ --bindir=/bin --libdir=/lib --disable-imlib2 --disable-doc
make pkglibdir=/lib pkgdatadir=/data bindir=/bin

# Install into our private directory
make install DESTDIR="${DESTDIR}" pkglibdir=/lib/ pkgdatadir=/ bindir=/bin/
cp COPYING COPYING.LGPL "${DESTDIR}/share/doc/libcaca-dev/"

mv "${DESTDIR}/bin/"* "${DESTDIR}/"
mv "${DESTDIR}/lib/"* "${DESTDIR}/"
i586-mingw32msvc-strip "${DESTDIR}/"*.exe
i586-mingw32msvc-strip "${DESTDIR}/"*.dll
rmdir "${DESTDIR}/bin"
rmdir "${DESTDIR}/lib"

mkdir "${DESTDIR}/doc"
for f in `ls "${DESTDIR}/share/doc/libcaca-dev/"`; do
   sed -e 's/$//' < "${DESTDIR}/share/doc/libcaca-dev/${f}" > "${DESTDIR}/doc/${f}.txt"
done
rm -Rf "${DESTDIR}/share"
rm -Rf "${DESTDIR}/man"
rm -Rf "${DESTDIR}/include"
rm -f "${DESTDIR}/caca-config"
rm -f "${DESTDIR}/"*.a
rm -f "${DESTDIR}/"*.la

# Pack the directory
zip "${DIRNAME}.zip" `find "${DIRNAME}"`
rm -Rf "${DIRNAME}"

