#!/bin/sh

export MAKEFLAGS=""
top_srcdir="$(make -s echo-topdir)"

#
# Check that we have no tabs or trailing spaces in the source code
#
nfails=0
nfiles=0
nlines=0
for dir in $(make -s echo-dirs -C "${top_srcdir}"); do
  if [ ! -d "${top_srcdir}/${dir}" ]; then continue; fi
  for x in $(make -s echo-sources -C "${top_srcdir}/${dir}"); do
    case "$x" in
      *.c|*.cpp|*.h|*.m|*.php|*.cs|*.java|*.py|*.pl)
        nfiles=$(($nfiles + 1));
        nlines=$(($nlines + `grep -c . "${top_srcdir}/${dir}/$x"`)) ;;
      *)
        continue ;;
    esac
    if grep '[[:space:]]$' "${top_srcdir}/${dir}/$x" >/dev/null 2>&1; then
      echo "error: ${dir}/$x contains trailing spaces"
      nfails=$(($nfails + 1))
    fi
    if grep '	' "${top_srcdir}/${dir}/$x" >/dev/null 2>&1; then
      echo "error: ${dir}/$x contains tabs"
      nfails=$(($nfails + 1))
    fi
  done
done

echo "$nfiles files, $nlines lines, $nfails errors in source code"

if test "$nfails" != "0"; then
  exit 1
fi

exit 0

