.TH caca-spritedit 1 "2003-11-22" "libcaca"
.SH NAME
caca-spritedit \- libcaca's sprite viewer
.SH SYNOPSIS
.B caca-spritedit FILE
.RI
.SH DESCRIPTION
This is a simple sprite viewer for libcaca sprites. It will evolve into a
full featured sprite editor.
.PP
Use + and - keys to browse through the sprite's frames, q to quit.
.SH EXAMPLE
caca-spritedit /usr/share/libcaca/caca.txt
.SH AUTHOR
This manual page was written by Sam Hocevar <sam@zoy.org>
