.TH libcaca 1 "2004-1-6" "libcaca"
.SH NAME
cacademo, cacaball, cacafire, cacamoir, cacaplas \- libcaca's demonstration
applications
.SH SYNOPSIS
cacademo
.PP
cacaball
.PP
cacafire
.PP
cacamoir
.PP
cacaplas
.RI
.SH DESCRIPTION
This manual page documents briefly the cacademo, cacaball, cacafire, cacamoir
and cacaplas programs.
.PP
.B cacademo
is a simple demo which demonstrates some features of the libcaca
library. The main menu lists available keys and their actions. To
exit a particular demo, press any key.
.PP
.B cacaball
displays ASCII art metaballs.
.PP
.B cacafire
displays burning ASCII art flames.
.PP
.B cacamoir
displays a coloured ASCII art moire pattern of concentric circles.
.PP
.B cacaplas
displays an old school ASCII art plasma effect.
.SH BUGS
Please report any bugs you find to <libcaca@lists.zoy.org>.
.SH LICENSE
cacademo, cacaball, cacamoir and cacaplas are covered by the Do What The
Fuck You Want Public License (WTFPL).
cacafire is covered by the GNU Lesser General Public License (LGPL).
.SH AUTHORS
.B cacademo, cacamoir
and this manual page were written by Sam Hocevar <sam@zoy.org>.
.PP
.B cacaball
was written by Jean-Yves Lamoureux <jylam@lnxscene.org>,
.B cacafire
is a port of AAlib's
.B aafire
written by Jan Hubicka <hubicka@freesoft.cz> and
.B cacaplas
is a port of an SDL plasma effect written and put in the public domain by
Michele Bini <mibin@tin.it>.
.SH SEE ALSO
cacaview(1), aafire(1)
