.TH caca-demo 1 "2003-11-22" "libcaca"
.SH NAME
caca-demo \- libcaca's demonstration application
.SH SYNOPSIS
.B caca-demo
.RI
.SH DESCRIPTION
This is a simple demo which demonstrates some features of the libcaca
library.
.PP
The main menu lists available keys and their actions. To exit a particular
demo, press any key.
.SH AUTHOR
This manual page was written by Sam Hocevar <sam@zoy.org>
