.TH libcaca 1 "2006-9-23" "libcaca"
.SH NAME
cacademo, cacafire \- libcaca's demonstration applications
.SH SYNOPSIS
cacademo
.PP
cacafire
.RI
.SH DESCRIPTION
This manual page documents briefly the cacademo and cacafire programs.
.PP
.B cacademo
displays ASCII art effects with animated transitions: metaballs, moire pattern
of concentric circles, old school plasma, Matrix-like scrolling.
.PP
.B cacafire
displays burning ASCII art flames.
.SH KEYS
.TP
.B Enter
forces an effect transition to happen
.TP
.B Space
pauses and resumes the program
.TP
.B Esc
exits the program
.SH BUGS
Please report any bugs you find to <libcaca@lists.zoy.org>.
.SH LICENSE
cacademo is covered by the Do What the Fuck You Want to Public License
(WTFPL). cacafire is covered by the GNU Lesser General Public License (LGPL).
.SH AUTHORS
.B cacademo's
moire and matrix effects and this manual page were written by Sam Hocevar
<sam@hocevar.net>.
.PP
.B cacademo's
metaball effect was written by Jean-Yves Lamoureux <jylam@lnxscene.org>,
.B cacafire
is a port of AAlib's
.B aafire
written by Jan Hubicka <hubicka@freesoft.cz> and
.B cacademo's
plasma effect is a port of an SDL plasma effect written and put in the
public domain by Michele Bini <mibin@tin.it>.
.SH SEE ALSO
cacaview(1), aafire(1)
